eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: eureka-client
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG
      profile: dev
env:
  dev: "git开发new"
